//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class AlertInterval
    {
        public AlertInterval()
        {
            this.Alerts = new HashSet<Alert>();
        }
    
        public int P_IdInterval { get; set; }
        public string A_Name { get; set; }
        public int A_Time { get; set; }
        public bool A_Enabled { get; set; }
        public string A_Code { get; set; }
    
        public virtual ICollection<Alert> Alerts { get; set; }
    }
}
