//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class Alert
    {
        public Alert()
        {
            this.AlertFeatures = new HashSet<AlertFeature>();
            this.PeopleToBeContacteds = new HashSet<PeopleToBeContacted>();
        }
    
        public int P_IDAlert { get; set; }
        public int F_User_ID { get; set; }
        public int F_IDInterval { get; set; }
        public int F_PublishableItemType { get; set; }
        public string A_AlertName { get; set; }
        public string A_Description { get; set; }
        public DateTime A_DateCreation { get; set; }
        public Nullable<DateTime> A_LastSentDate { get; set; }
        public bool A_Enabled { get; set; }
        public string A_URL { get; set; }
        public string A_Find { get; set; }
    
        public virtual ICollection<AlertFeature> AlertFeatures { get; set; }
        public virtual AlertInterval AlertInterval { get; set; }
        public virtual PublishableItemType PublishableItemType { get; set; }
        public virtual AlertUser AlertUser { get; set; }
        public virtual ICollection<PeopleToBeContacted> PeopleToBeContacteds { get; set; }
    }
}
