//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class AppliedDiscountCoupon
    {
        public int Id { get; set; }
        public Nullable<int> idDiscountCoupon { get; set; }
        public DateTime ExchangeDate { get; set; }
        public int idUserWhoSpent { get; set; }
        public int PurchaseOrder_id { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual DiscountCoupon DiscountCoupon { get; set; }
        public virtual User User { get; set; }
    }
}
