//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class AuditRememberDay
    {
        public int Id { get; set; }
        public Nullable<int> RememberDayId { get; set; }
        public string State { get; set; }
        public DateTime DateOfEntryIntoTheState { get; set; }
        public bool SentMail { get; set; }
    
        public virtual RememberDay RememberDay { get; set; }
    }
}
