//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class AuditPublicationPaperDate
    {
        public int P_Id { get; set; }
        public Nullable<int> F_PublicationPaperDate_Id { get; set; }
        public string A_State { get; set; }
        public DateTime A_DateOfEntryIntoTheState { get; set; }
    
        public virtual PublicationPaperDate PublicationPaperDate { get; set; }
    }
}
