//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class AuditClarin365TrackOfTransaction
    {
        public int P_Id { get; set; }
        public Nullable<int> F_Clarin365TrackOfTransaction_Id { get; set; }
        public DateTime A_DateOfEntryIntoTheState { get; set; }
        public int F_State_Id { get; set; }
        public string A_Response { get; set; }
    
        public virtual Clarin365TrackOfTransaction Clarin365TrackOfTransaction { get; set; }
    }
}
