//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class AutoPublication
    {
        public AutoPublication()
        {
            this.GeoLocationItemAutoPublications = new HashSet<GeoLocationItemAutoPublication>();
            this.VehicleBrandAutoPublications = new HashSet<VehicleBrandAutoPublication>();
            this.AutoPublicationVehicleModelYears = new HashSet<AutoPublicationVehicleModelYear>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public string Text { get; set; }
        public string Url { get; set; }
        public Nullable<bool> Default { get; set; }
        public string Discriminator { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<GeoLocationItemAutoPublication> GeoLocationItemAutoPublications { get; set; }
        public virtual ICollection<VehicleBrandAutoPublication> VehicleBrandAutoPublications { get; set; }
        public virtual ICollection<AutoPublicationVehicleModelYear> AutoPublicationVehicleModelYears { get; set; }
    }
}
