//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class BackOfficeLog
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public string Action { get; set; }
        public string Content { get; set; }
        public Nullable<DateTime> CreationDate { get; set; }
        public string BackOfficereasons { get; set; }
        public Nullable<int> PublicationOrderId { get; set; }
        public Nullable<int> SuscriptionId { get; set; }
        public Nullable<int> PurchaseOrderId { get; set; }
    }
}
