//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAutos.Automation.Model.Database
{
    public partial class BannerInfo
    {
        public int Id { get; set; }
        public string Section { get; set; }
        public string Name { get; set; }
        public int Height { get; set; }
        public int Width { get; set; }
        public bool UseIframe { get; set; }
        public string Provider { get; set; }
        public int FormatId { get; set; }
        public string Server { get; set; }
        public string Behaviour { get; set; }
        public string Zone { get; set; }
        public string Order { get; set; }
        public string Parameters { get; set; }
        public bool Active { get; set; }
    }
}
