//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class BrandSavingPlan
    {
        public int P_Id { get; set; }
        public string A_CommercialName { get; set; }
        public Nullable<int> F_Brand_Id { get; set; }
        public Nullable<bool> A_Visible { get; set; }
    
        public virtual VehicleBrand VehicleBrand { get; set; }
    }
}
