//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class BusinessDomain
    {
        public BusinessDomain()
        {
            this.Tags = new HashSet<Tag>();
            this.Tags1 = new HashSet<Tag>();
            this.PaymentMethodAvailabilities = new HashSet<PaymentMethodAvailability>();
            this.LocalizedMessages = new HashSet<LocalizedMessage>();
            this.MessageBrokers = new HashSet<MessageBroker>();
            this.Discounts = new HashSet<Discount>();
            this.Users = new HashSet<User>();
            this.ProductOfferings = new HashSet<ProductOffering>();
            this.Currencies = new HashSet<Currency>();
            this.Fuels = new HashSet<Fuel>();
            this.ImageFormats = new HashSet<ImageFormat>();
            this.PublishableItemTypes = new HashSet<PublishableItemType>();
        }
    
        public int Id { get; set; }
        public int idDefaultCurrency { get; set; }
        public string SecondLevelDomain { get; set; }
    
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<Tag> Tags1 { get; set; }
        public virtual ICollection<PaymentMethodAvailability> PaymentMethodAvailabilities { get; set; }
        public virtual ICollection<LocalizedMessage> LocalizedMessages { get; set; }
        public virtual ICollection<MessageBroker> MessageBrokers { get; set; }
        public virtual ICollection<Discount> Discounts { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual ICollection<ProductOffering> ProductOfferings { get; set; }
        public virtual ICollection<Currency> Currencies { get; set; }
        public virtual ICollection<Fuel> Fuels { get; set; }
        public virtual ICollection<ImageFormat> ImageFormats { get; set; }
        public virtual ICollection<PublishableItemType> PublishableItemTypes { get; set; }
    }
}
