//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class Campaign
    {
        public Campaign()
        {
            this.ClientUsers = new HashSet<ClientUser>();
        }
    
        public int P_Id { get; set; }
        public string A_Name { get; set; }
        public string A_UrlSuffix { get; set; }
        public Nullable<bool> A_LandingEnabled { get; set; }
        public Nullable<DateTime> A_DueDate { get; set; }
    
        public virtual ICollection<ClientUser> ClientUsers { get; set; }
    }
}
