//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class Car
    {
        public int Vehicle_id { get; set; }
        public int idVersion { get; set; }
        public Nullable<bool> ShowCatalogInfo { get; set; }
    
        public virtual VehicleVersion VehicleVersion { get; set; }
        public virtual SavingPlan SavingPlan { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual NewCar NewCar { get; set; }
        public virtual UsedCar UsedCar { get; set; }
    }
}
