//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class CatalogSponsor
    {
        public CatalogSponsor()
        {
            this.CatalogSponsorCompares = new HashSet<CatalogSponsorCompare>();
        }
    
        public int Id { get; set; }
        public int ModelId { get; set; }
        public bool Enabled { get; set; }
        public string Mails { get; set; }
        public int VersionId { get; set; }
        public bool EnabledHome { get; set; }
        public string SmallTag { get; set; }
    
        public virtual ICollection<CatalogSponsorCompare> CatalogSponsorCompares { get; set; }
        public virtual VehicleVersion VehicleVersion { get; set; }
        public virtual VehicleModel VehicleModel { get; set; }
    }
}
