//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAutos.Automation.Model.Database
{
    public partial class CatalogMetadata
    {
        public long P_Id { get; set; }
        public long F_CatalogLevel_Id { get; set; }
        public long A_Catalog_Id { get; set; }
        public long A_Country_Id { get; set; }
        public long F_MetadataType_Id { get; set; }
        public string A_Value { get; set; }
    
        public virtual CatalogLevel CatalogLevel { get; set; }
        public virtual MetadataType MetadataType { get; set; }
    }
}
