//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class Clarin365TrackOfTransaction
    {
        public Clarin365TrackOfTransaction()
        {
            this.AuditClarin365TrackOfTransaction = new HashSet<AuditClarin365TrackOfTransaction>();
        }
    
        public int P_Id { get; set; }
        public Nullable<int> F_PurchaseOrder_Id { get; set; }
        public string A_CredencialCode { get; set; }
        public int F_State_Id { get; set; }
        public DateTime A_InputCodeDate { get; set; }
        public Nullable<DateTime> A_PaidDate { get; set; }
        public Nullable<int> A_IdSucursal { get; set; }
        public Nullable<int> A_IdBeneficio { get; set; }
        public string A_TransactionType { get; set; }
        public Nullable<decimal> A_Amount { get; set; }
        public Nullable<decimal> A_DiscountAmount { get; set; }
    
        public virtual ICollection<AuditClarin365TrackOfTransaction> AuditClarin365TrackOfTransaction { get; set; }
        public virtual Publication Publication { get; set; }
    }
}
