//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class ClientUser
    {
        public ClientUser()
        {
            this.Suscriptions = new HashSet<Suscription>();
            this.PeopleContacteds = new HashSet<PeopleContacted>();
            this.VehicleModelSellerClients = new HashSet<VehicleModelSellerClient>();
            this.ClientUser1 = new HashSet<ClientUser>();
            this.VehicleBrandSellerClients = new HashSet<VehicleBrandSellerClient>();
            this.Campaigns = new HashSet<Campaign>();
            this.VehicleBrands = new HashSet<VehicleBrand>();
        }
    
        public int User_id { get; set; }
        public Nullable<int> Manager { get; set; }
        public Nullable<int> Site { get; set; }
    
        public virtual ICollection<Suscription> Suscriptions { get; set; }
        public virtual ICollection<PeopleContacted> PeopleContacteds { get; set; }
        public virtual ICollection<VehicleModelSellerClient> VehicleModelSellerClients { get; set; }
        public virtual Site Site1 { get; set; }
        public virtual ICollection<ClientUser> ClientUser1 { get; set; }
        public virtual ClientUser ClientUser2 { get; set; }
        public virtual ICollection<VehicleBrandSellerClient> VehicleBrandSellerClients { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Campaign> Campaigns { get; set; }
        public virtual ICollection<VehicleBrand> VehicleBrands { get; set; }
    }
}
