//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class Client
    {
        public Client()
        {
            this.Sites = new HashSet<Site>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Cuit { get; set; }
        public string Website { get; set; }
        public int TaxCondition { get; set; }
        public int State { get; set; }
        public string TaxStreet { get; set; }
        public string TaxStreetNumber { get; set; }
        public string TaxFloor { get; set; }
        public string TaxDepartment { get; set; }
        public string TaxZipCode { get; set; }
        public int TaxGeoLocation { get; set; }
        public string SapBillingCode { get; set; }
        public string TaxName { get; set; }
        public int GeoLocation { get; set; }
        public Nullable<int> PhoneNumberId { get; set; }
    
        public virtual ClientState ClientState { get; set; }
        public virtual GeoLocationItem GeoLocationItem { get; set; }
        public virtual PhoneNumber PhoneNumber { get; set; }
        public virtual TaxCondition TaxCondition1 { get; set; }
        public virtual GeoLocationItem GeoLocationItem1 { get; set; }
        public virtual ICollection<Site> Sites { get; set; }
    }
}
