//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAutos.Automation.Model.Database
{
    public partial class ContactButtonConfiguration
    {
        public int Id { get; set; }
        public int ContactButtonId { get; set; }
        public int PublishableItemTypeId { get; set; }
        public int UserTypeId { get; set; }
    
        public virtual ContactButton ContactButton { get; set; }
        public virtual PublishableItemType PublishableItemType { get; set; }
    }
}
