//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class ContactData
    {
        public ContactData()
        {
            this.PeopleToBeContacteds = new HashSet<PeopleToBeContacted>();
        }
    
        public long P_Id { get; set; }
        public string A_Name { get; set; }
        public string A_Email { get; set; }
        public string A_Telephone { get; set; }
        public bool A_AcceptToReceiveInfo { get; set; }
        public Nullable<int> F_Locality_Id { get; set; }
        public Nullable<int> F_Location_Id { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ICollection<PeopleToBeContacted> PeopleToBeContacteds { get; set; }
        public virtual GeoLocationItem GeoLocationItem { get; set; }
    }
}
