//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class Conversation
    {
        public Conversation()
        {
            this.RememberDays = new HashSet<RememberDay>();
            this.RememberDayItems = new HashSet<RememberDayItem>();
            this.Conversation1 = new HashSet<Conversation>();
            this.Messages = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public DateTime CreationDate { get; set; }
        public bool AcceptsToBeContacted { get; set; }
        public string ContactName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public int SourceConversationId { get; set; }
        public Nullable<int> PublicationId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> ConversationParentId { get; set; }
        public Nullable<Guid> KeyGuidContact { get; set; }
        public Nullable<int> AuthorId { get; set; }
    
        public virtual Site Site { get; set; }
        public virtual ICollection<RememberDay> RememberDays { get; set; }
        public virtual ICollection<RememberDayItem> RememberDayItems { get; set; }
        public virtual ICollection<Conversation> Conversation1 { get; set; }
        public virtual Conversation Conversation2 { get; set; }
        public virtual Publication Publication { get; set; }
        public virtual SourceConversation SourceConversation { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
