//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class CreditPack
    {
        public CreditPack()
        {
            this.CreditPackItems = new HashSet<CreditPackItem>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int StateId { get; set; }
        public int ProductOfferingId { get; set; }
        public Nullable<int> PurchaseOrderId { get; set; }
        public DateTime CreationDate { get; set; }
        public Nullable<DateTime> ActivationDate { get; set; }
        public Nullable<DateTime> ExpirationDate { get; set; }
        public Nullable<DateTime> EndDate { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual CreditPackState CreditPackState { get; set; }
        public virtual ProductOffering ProductOffering { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<CreditPackItem> CreditPackItems { get; set; }
    }
}
