//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class Currency
    {
        public Currency()
        {
            this.PaymentTickets = new HashSet<PaymentTicket>();
            this.PaymentTickets1 = new HashSet<PaymentTicket>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.PurchaseOrderItems = new HashSet<PurchaseOrderItem>();
            this.BusinessDomains = new HashSet<BusinessDomain>();
            this.ProductOfferingPrices = new HashSet<ProductOfferingPrice>();
            this.PublishableItems = new HashSet<PublishableItem>();
            this.PublishableItems1 = new HashSet<PublishableItem>();
            this.BusinessDomains1 = new HashSet<BusinessDomain>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string idSymbol { get; set; }
        public Nullable<decimal> Exchange { get; set; }
        public string SourceCurrencyId { get; set; }
        public string TargetCurrencyId { get; set; }
    
        public virtual ICollection<PaymentTicket> PaymentTickets { get; set; }
        public virtual ICollection<PaymentTicket> PaymentTickets1 { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<PurchaseOrderItem> PurchaseOrderItems { get; set; }
        public virtual ICollection<BusinessDomain> BusinessDomains { get; set; }
        public virtual ICollection<ProductOfferingPrice> ProductOfferingPrices { get; set; }
        public virtual ICollection<PublishableItem> PublishableItems { get; set; }
        public virtual ICollection<PublishableItem> PublishableItems1 { get; set; }
        public virtual ICollection<BusinessDomain> BusinessDomains1 { get; set; }
    }
}
