//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class CustomerGroup
    {
        public CustomerGroup()
        {
            this.UserCustomerGroups = new HashSet<UserCustomerGroup>();
        }
    
        public int P_Id { get; set; }
        public string A_GroupName { get; set; }
        public Nullable<short> A_PriorityLevel { get; set; }
        public string A_Discriminator { get; set; }
        public bool A_ActiveState { get; set; }
    
        public virtual ICollection<UserCustomerGroup> UserCustomerGroups { get; set; }
    }
}
