//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class DiscountCoupon
    {
        public DiscountCoupon()
        {
            this.AppliedDiscountCoupons = new HashSet<AppliedDiscountCoupon>();
        }
    
        public int Id { get; set; }
        public string CouponIdentificationCode { get; set; }
        public DateTime ValidFromDate { get; set; }
        public Nullable<DateTime> DueDate { get; set; }
        public int idDiscount { get; set; }
        public string State { get; set; }
        public Nullable<int> idUser { get; set; }
        public DateTime CreationDate { get; set; }
        public string CodeBatch { get; set; }
        public int Quantity { get; set; }
        public int QuantityUsed { get; set; }
        public string CreatingUser { get; set; }
    
        public virtual ICollection<AppliedDiscountCoupon> AppliedDiscountCoupons { get; set; }
        public virtual Discount Discount { get; set; }
        public virtual User User { get; set; }
    }
}
