//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class EndUser
    {
        public int User_id { get; set; }
        public Nullable<int> idGeolocationItem { get; set; }
        public Nullable<bool> A_AlertUser { get; set; }
        public Nullable<DateTime> A_DateAlertToPart { get; set; }
    
        public virtual GeoLocationItem GeoLocationItem { get; set; }
        public virtual User User { get; set; }
    }
}
