//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class Feature
    {
        public Feature()
        {
            this.ListedVehicleFeatures = new HashSet<ListedVehicleFeature>();
        }
    
        public long P_Id { get; set; }
        public string A_FeatureName { get; set; }
        public long F_FeaturesGroup_Id { get; set; }
        public bool A_MayHaveAnEditableValue { get; set; }
        public bool A_ActiveState { get; set; }
    
        public virtual ICollection<ListedVehicleFeature> ListedVehicleFeatures { get; set; }
        public virtual FeatureGroup FeatureGroup { get; set; }
    }
}
