//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class Fuel
    {
        public Fuel()
        {
            this.Vehicles = new HashSet<Vehicle>();
            this.BusinessDomains = new HashSet<BusinessDomain>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SeoFriendlyName { get; set; }
        public Nullable<bool> Enabled { get; set; }
    
        public virtual ICollection<Vehicle> Vehicles { get; set; }
        public virtual ICollection<BusinessDomain> BusinessDomains { get; set; }
    }
}
