//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAutos.Automation.Model.Database
{
    public partial class HubVehicleSpecConversion
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string HubCode { get; set; }
        public string DeAutosCode { get; set; }
    }
}
