//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class ImageFormat
    {
        public ImageFormat()
        {
            this.BusinessDomains = new HashSet<BusinessDomain>();
        }
    
        public int Id { get; set; }
        public string FormatKey { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public string FormatName { get; set; }
        public bool IsDefault { get; set; }
        public bool Enabled { get; set; }
    
        public virtual ICollection<BusinessDomain> BusinessDomains { get; set; }
    }
}
