//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class ImporterProcessLog
    {
        public ImporterProcessLog()
        {
            this.HubPublicationErrorDetails = new HashSet<HubPublicationErrorDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<DateTime> StartDate { get; set; }
        public Nullable<DateTime> EndDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> IdLastProcessed { get; set; }
        public string ImporterType { get; set; }
    
        public virtual ICollection<HubPublicationErrorDetail> HubPublicationErrorDetails { get; set; }
    }
}
