//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAutos.Automation.Model.Database
{
    public partial class ImportUser
    {
        public int UserId { get; set; }
        public bool System { get; set; }
        public int Type { get; set; }
    
        public virtual User User { get; set; }
    }
}
