//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class IndexAttributeEntity
    {
        public int Id { get; set; }
        public string Attr_value_type { get; set; }
        public Nullable<int> Attr_id { get; set; }
        public string Attr_value { get; set; }
        public string Attr_type { get; set; }
        public Nullable<int> IndexEntity_id { get; set; }
    
        public virtual IndexEntity IndexEntity { get; set; }
    }
}
