//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class IndexFeatureEntity
    {
        public int Id { get; set; }
        public Nullable<int> IndexEntity_Id { get; set; }
        public int Feature_Id { get; set; }
        public string Feature_Key { get; set; }
    
        public virtual IndexEntity IndexEntity { get; set; }
    }
}
