//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class IndexEntity
    {
        public IndexEntity()
        {
            this.IndexAttributeEntities = new HashSet<IndexAttributeEntity>();
            this.IndexFeatureEntities = new HashSet<IndexFeatureEntity>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FuelId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> VersionId { get; set; }
        public string Year { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> GeoStateId { get; set; }
        public Nullable<int> GeoRegionId { get; set; }
        public Nullable<int> GeoCityId { get; set; }
        public Nullable<int> UploadedPhotosQuantity { get; set; }
        public Nullable<int> Km { get; set; }
        public Nullable<int> ColorId { get; set; }
        public Nullable<int> PublicationId { get; set; }
        public Nullable<int> VisitCount { get; set; }
        public string SearchResultSection { get; set; }
        public Nullable<int> IndexWeight { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserType { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> SegmentId { get; set; }
        public Nullable<int> PublishableItemTypeId { get; set; }
        public Nullable<DateTime> StartDate { get; set; }
        public Nullable<DateTime> EndDate { get; set; }
        public Nullable<decimal> PriceAbsolute { get; set; }
        public string Sellercomments { get; set; }
        public Nullable<int> PublishableItemId { get; set; }
        public Nullable<DateTime> LastIndexTime { get; set; }
        public Nullable<bool> CheckPrice { get; set; }
        public Nullable<DateTime> LastModifiedDate { get; set; }
        public Nullable<int> PublicationGroupedByTypeAndWeight { get; set; }
        public string Financing { get; set; }
        public Nullable<decimal> PureFeeValue { get; set; }
        public Nullable<decimal> AverageFeeValue { get; set; }
        public Nullable<int> NumberOfFees { get; set; }
        public Nullable<int> NumberOfAgreedDeliveryFee { get; set; }
        public Nullable<int> SavingPlanTypeId { get; set; }
        public Nullable<int> NumberOfPaidFees { get; set; }
        public Nullable<decimal> TransferAmmount { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<bool> ShowInHome { get; set; }
        public Nullable<int> MessageContactCount { get; set; }
        public string BrandName { get; set; }
        public string ModelName { get; set; }
        public string VersionName { get; set; }
        public string SegmentName { get; set; }
        public string GeoStateName { get; set; }
        public string GeoRegionName { get; set; }
        public string GeoCityName { get; set; }
        public string ItemConditionName { get; set; }
        public string ColorName { get; set; }
        public string FuelName { get; set; }
        public Nullable<bool> IsPublicationClone { get; set; }
        public bool AutoRepublication { get; set; }
        public Nullable<DateTime> ExpirationDate { get; set; }
        public bool IsSavingPlanTransfer { get; set; }
        public string Plate { get; set; }
        public Nullable<int> PaymentOptionId { get; set; }
        public decimal AdvancePayment { get; set; }
        public int SinceQuota { get; set; }
        public decimal Patenting { get; set; }
        public string VideoUrl { get; set; }
        public bool CanDelete { get; set; }
    
        public virtual ICollection<IndexAttributeEntity> IndexAttributeEntities { get; set; }
        public virtual ICollection<IndexFeatureEntity> IndexFeatureEntities { get; set; }
    }
}
