//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class ListedVehicle
    {
        public ListedVehicle()
        {
            this.ListedVehicleFeatures = new HashSet<ListedVehicleFeature>();
        }
    
        public long P_Id { get; set; }
        public int A_Year { get; set; }
        public long A_Country_Id { get; set; }
        public long F_VehicleType_Id { get; set; }
        public int F_VehicleVersion_Id { get; set; }
        public bool A_SellAs0km { get; set; }
    
        public virtual ICollection<ListedVehicleFeature> ListedVehicleFeatures { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        public virtual VehicleVersion VehicleVersion { get; set; }
    }
}
