//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class ListedVehicleFeature
    {
        public ListedVehicleFeature()
        {
            this.ListedVehicleFeatureValues = new HashSet<ListedVehicleFeatureValue>();
        }
    
        public long P_Id { get; set; }
        public long F_Feature_Id { get; set; }
        public long F_ListedVehicle_Id { get; set; }
        public long F_FeatureType_Id { get; set; }
        public Nullable<double> A_OptionalPrice { get; set; }
        public Nullable<int> A_OptionalCurrency { get; set; }
    
        public virtual Feature Feature { get; set; }
        public virtual FeatureType FeatureType { get; set; }
        public virtual ListedVehicle ListedVehicle { get; set; }
        public virtual ICollection<ListedVehicleFeatureValue> ListedVehicleFeatureValues { get; set; }
    }
}
