//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class Location
    {
        public Location()
        {
            this.ContactDatas = new HashSet<ContactData>();
        }
    
        public int P_Id { get; set; }
        public int F_LocationType_Id { get; set; }
        public Nullable<int> F_GeolocationItem_Id { get; set; }
        public Nullable<int> F_PrincingZone_Id { get; set; }
        public Nullable<int> A_ShowOrder { get; set; }
    
        public virtual PricingZone PricingZone { get; set; }
        public virtual ICollection<ContactData> ContactDatas { get; set; }
        public virtual GeoLocationItem GeoLocationItem { get; set; }
        public virtual LocationType LocationType { get; set; }
    }
}
