//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAutos.Automation.Model.Database
{
    public partial class LocalizedMessage
    {
        public long Id { get; set; }
        public long LocalizedMessageFormId { get; set; }
        public int BusinessDomainId { get; set; }
        public string Key { get; set; }
        public string Message { get; set; }
    
        public virtual BusinessDomain BusinessDomain { get; set; }
        public virtual LocalizedMessageForm LocalizedMessageForm { get; set; }
    }
}
