//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class MailDepositBlacklist
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public DateTime Blacklisted_Date { get; set; }
    }
}
