//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class MessageQueueParam
    {
        public int Id { get; set; }
        public Nullable<int> MessageQueueId { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
    
        public virtual MessageQueue MessageQueue { get; set; }
    }
}
