//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class MessageQueueResponseDetail
    {
        public int Id { get; set; }
        public Nullable<int> MessageQueueId { get; set; }
        public DateTime SendDate { get; set; }
        public string Response { get; set; }
        public int MessageQueueStatusId { get; set; }
    
        public virtual MessageQueue MessageQueue { get; set; }
        public virtual MessageQueueStatu MessageQueueStatu { get; set; }
    }
}
