//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class MessageQueueStatu
    {
        public MessageQueueStatu()
        {
            this.MessageQueues = new HashSet<MessageQueue>();
            this.MessageQueueResponseDetails = new HashSet<MessageQueueResponseDetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<MessageQueue> MessageQueues { get; set; }
        public virtual ICollection<MessageQueueResponseDetail> MessageQueueResponseDetails { get; set; }
    }
}
