//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class MessageTemplate
    {
        public MessageTemplate()
        {
            this.MessageBrokers = new HashSet<MessageBroker>();
            this.MessageQueues = new HashSet<MessageQueue>();
        }
    
        public int Id { get; set; }
        public int MessageSendTypeId { get; set; }
        public string Subject { get; set; }
        public short Priority { get; set; }
        public bool SendWarning { get; set; }
        public int MessageActionAfterSentId { get; set; }
    
        public virtual ContactServiceTemplate ContactServiceTemplate { get; set; }
        public virtual ICollection<MessageBroker> MessageBrokers { get; set; }
        public virtual ICollection<MessageQueue> MessageQueues { get; set; }
        public virtual MessageSendType MessageSendType { get; set; }
        public virtual PlanisysTemplate PlanisysTemplate { get; set; }
        public virtual SmtpTemplate SmtpTemplate { get; set; }
    }
}
