//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class Message
    {
        public Message()
        {
            this.MessageQueues = new HashSet<MessageQueue>();
        }
    
        public int Id { get; set; }
        public int ConversationId { get; set; }
        public string Ip { get; set; }
        public string Content { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public DateTime Timestamp { get; set; }
        public int SourceSectionId { get; set; }
        public bool SourceSectionInModal { get; set; }
        public int MessageTypeId { get; set; }
        public int MessageSubTypeId { get; set; }
        public bool Viewed { get; set; }
    
        public virtual Conversation Conversation { get; set; }
        public virtual MessageSubType MessageSubType { get; set; }
        public virtual MessageType MessageType { get; set; }
        public virtual SourceSection SourceSection { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<MessageQueue> MessageQueues { get; set; }
    }
}
