//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class MessageQueue
    {
        public MessageQueue()
        {
            this.MessageQueueParams = new HashSet<MessageQueueParam>();
            this.MessageQueueResponseDetails = new HashSet<MessageQueueResponseDetail>();
        }
    
        public int Id { get; set; }
        public int MessageTemplateId { get; set; }
        public DateTime CreateDate { get; set; }
        public int MessageQueueStatusId { get; set; }
        public string ToAddress { get; set; }
        public string ReplyTo { get; set; }
        public Nullable<int> MessageId { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual MessageQueueStatu MessageQueueStatu { get; set; }
        public virtual MessageTemplate MessageTemplate { get; set; }
        public virtual ICollection<MessageQueueParam> MessageQueueParams { get; set; }
        public virtual ICollection<MessageQueueResponseDetail> MessageQueueResponseDetails { get; set; }
    }
}
