//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class MessageBroker
    {
        public int Id { get; set; }
        public Nullable<int> MessageTemplateId { get; set; }
        public bool RedirectMessage { get; set; }
        public int BusinessDomainId { get; set; }
        public int MessageKeyBrokerId { get; set; }
    
        public virtual BusinessDomain BusinessDomain { get; set; }
        public virtual MessageKeyBroker MessageKeyBroker { get; set; }
        public virtual MessageTemplate MessageTemplate { get; set; }
    }
}
