//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class MetadataType
    {
        public MetadataType()
        {
            this.CatalogMetadatas = new HashSet<CatalogMetadata>();
        }
    
        public long P_Id { get; set; }
        public string A_Description { get; set; }
        public string A_Code { get; set; }
        public Nullable<bool> A_ActiveState { get; set; }
    
        public virtual ICollection<CatalogMetadata> CatalogMetadatas { get; set; }
    }
}
