//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAutos.Automation.Model.Database
{
    public partial class PaperBrandModelConversion
    {
        public int Id { get; set; }
        public string MarcaClarin { get; set; }
        public string ModeloClarin { get; set; }
        public string VersionClarin { get; set; }
        public string MarcaDeautos { get; set; }
        public string ModeloDeautos { get; set; }
    }
}
