//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class PaymentMethodAvailability
    {
        public int Id { get; set; }
        public Nullable<DateTime> ValidSinceDate { get; set; }
        public Nullable<DateTime> ValidThrought { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<int> idPaymentTicketPaymentMethod { get; set; }
        public Nullable<int> idBusinessDomain { get; set; }
    
        public virtual BusinessDomain BusinessDomain { get; set; }
    }
}
