//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class PaymentMethod
    {
        public PaymentMethod()
        {
            this.PaymentTicketGatewayRequests = new HashSet<PaymentTicketGatewayRequest>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> PaymentMethodInBackOffice { get; set; }
        public Nullable<bool> PaymentMethodInFrontEnd { get; set; }
        public Nullable<bool> PaymentMethodOnline { get; set; }
        public Nullable<bool> PaymentMethodUserAccountCredit { get; set; }
        public Nullable<bool> PaymentMethodDiscount { get; set; }
        public string Discriminator { get; set; }
        public Nullable<bool> PaymentMethodMyBills { get; set; }
        public string GatewayCode { get; set; }
        public string MeansGatewayCode { get; set; }
        public string ImageUri { get; set; }
        public bool EndUserEnabled { get; set; }
    
        public virtual ICollection<PaymentTicketGatewayRequest> PaymentTicketGatewayRequests { get; set; }
    }
}
