//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class PaymentTicket
    {
        public int Id { get; set; }
        public string PaymentTicketState { get; set; }
        public Nullable<DateTime> CreationDate { get; set; }
        public Nullable<DateTime> ExpirationDate { get; set; }
        public Nullable<DateTime> PaymentDate { get; set; }
        public Nullable<decimal> SubtotalPaymentAmount { get; set; }
        public Nullable<decimal> TotalPaymentAmount { get; set; }
        public Nullable<bool> Clienting { get; set; }
        public string GatewayProvider { get; set; }
        public string GatewayPaymentMethodType { get; set; }
        public string GatewayPaymentMethod { get; set; }
        public string GatewayTicketId { get; set; }
        public int idPaymentTicketPaymentMethod { get; set; }
        public int idSubtotalPaymentAmountCurrency { get; set; }
        public int idTotalPaymentAmountCurrency { get; set; }
        public Nullable<int> PurchaseOrder_id { get; set; }
        public Nullable<DateTime> ExceededPaidDate { get; set; }
        public Nullable<DateTime> CancelledDate { get; set; }
        public Nullable<DateTime> RejectedDate { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual Currency Currency1 { get; set; }
    }
}
