//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class PaymentTicketGatewayResponse
    {
        public int Id { get; set; }
        public Nullable<DateTime> Date { get; set; }
        public Nullable<int> IdTicket { get; set; }
        public string Response { get; set; }
    }
}
