//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class PeopleToBeContacted
    {
        public PeopleToBeContacted()
        {
            this.AgenciesContacteds = new HashSet<AgenciesContacted>();
            this.PeopleContacteds = new HashSet<PeopleContacted>();
        }
    
        public long P_Id { get; set; }
        public Nullable<int> F_VehicleModel_Id { get; set; }
        public long F_ContactData_Id { get; set; }
        public DateTime A_ContactDate { get; set; }
        public string A_Message { get; set; }
        public Nullable<int> F_BannerCampaign_Id { get; set; }
        public Nullable<int> F_Alert_Id { get; set; }
        public Nullable<int> A_LandingVehicleModel_Id { get; set; }
        public Nullable<int> F_AgencyCampaign_Id { get; set; }
    
        public virtual BannerCampaign BannerCampaign { get; set; }
        public virtual Alert Alert { get; set; }
        public virtual ICollection<AgenciesContacted> AgenciesContacteds { get; set; }
        public virtual ContactData ContactData { get; set; }
        public virtual ICollection<PeopleContacted> PeopleContacteds { get; set; }
        public virtual VehicleModel VehicleModel { get; set; }
    }
}
