//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class PeopleContacted
    {
        public int P_Id { get; set; }
        public long F_PeopleToBeContacted_Id { get; set; }
        public DateTime A_SentDate { get; set; }
        public string A_SentMessage { get; set; }
        public string A_Recipient { get; set; }
        public Nullable<int> F_AgencyUser_Id { get; set; }
    
        public virtual ClientUser ClientUser { get; set; }
        public virtual PeopleToBeContacted PeopleToBeContacted { get; set; }
    }
}
