//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class PhoneContact
    {
        public int Id { get; set; }
        public int PublicationId { get; set; }
        public DateTime TimeStamp { get; set; }
        public int SourceSectionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CallerPhoneNumber { get; set; }
    
        public virtual SourceSection SourceSection { get; set; }
    }
}
