//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class Prelisting
    {
        public Prelisting()
        {
            this.PrelistingToVehicleModels = new HashSet<PrelistingToVehicleModel>();
            this.PrelistingToVehicleBrands = new HashSet<PrelistingToVehicleBrand>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public string Color { get; set; }
        public Nullable<int> Seconds { get; set; }
        public string TxColor { get; set; }
    
        public virtual ICollection<PrelistingToVehicleModel> PrelistingToVehicleModels { get; set; }
        public virtual ICollection<PrelistingToVehicleBrand> PrelistingToVehicleBrands { get; set; }
    }
}
