//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class PricingZone
    {
        public PricingZone()
        {
            this.SapZones = new HashSet<SapZone>();
            this.Locations = new HashSet<Location>();
            this.RememberDayItems = new HashSet<RememberDayItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SAPBillingCode { get; set; }
        public string TextReport { get; set; }
    
        public virtual ICollection<SapZone> SapZones { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<RememberDayItem> RememberDayItems { get; set; }
    }
}
