//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class ProcessTask
    {
        public ProcessTask()
        {
            this.ProcessSchedulers = new HashSet<ProcessScheduler>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Key { get; set; }
    
        public virtual ICollection<ProcessScheduler> ProcessSchedulers { get; set; }
    }
}
