//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class ProcessScheduler
    {
        public int Id { get; set; }
        public DateTime ExecutionToDay { get; set; }
        public int ProcessTaskId { get; set; }
        public int Status { get; set; }
        public Nullable<DateTime> Executed { get; set; }
    
        public virtual ProcessTask ProcessTask { get; set; }
    }
}
