//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class ProductOfferingPrice
    {
        public int P_Id { get; set; }
        public Nullable<int> F_ProductOffering_Id { get; set; }
        public decimal A_Price { get; set; }
        public int F_CustomCurrency_Id { get; set; }
        public DateTime A_AvaiableSinceDate { get; set; }
        public DateTime A_AvailableToDate { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual ProductOffering ProductOffering { get; set; }
    }
}
