//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class Product
    {
        public Product()
        {
            this.Discounts = new HashSet<Discount>();
            this.HubProductConversions = new HashSet<HubProductConversion>();
            this.ProductPackItems = new HashSet<ProductPackItem>();
            this.ProductPackItems1 = new HashSet<ProductPackItem>();
            this.ProductOfferings = new HashSet<ProductOffering>();
            this.Discounts1 = new HashSet<Discount>();
            this.ProductOfferings1 = new HashSet<ProductOffering>();
            this.ProductOfferings2 = new HashSet<ProductOffering>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Duration { get; set; }
        public bool Billiable { get; set; }
        public string SAPCode { get; set; }
        public string Discriminator { get; set; }
        public Nullable<int> PriorityLevel { get; set; }
        public bool ApplyDiscount { get; set; }
        public string SearchResultSection { get; set; }
        public int MaxPictureQuantity { get; set; }
        public int PublicationTypeId { get; set; }
    
        public virtual ICollection<Discount> Discounts { get; set; }
        public virtual ICollection<HubProductConversion> HubProductConversions { get; set; }
        public virtual ICollection<ProductPackItem> ProductPackItems { get; set; }
        public virtual ICollection<ProductPackItem> ProductPackItems1 { get; set; }
        public virtual ICollection<ProductOffering> ProductOfferings { get; set; }
        public virtual ICollection<Discount> Discounts1 { get; set; }
        public virtual ICollection<ProductOffering> ProductOfferings1 { get; set; }
        public virtual ICollection<ProductOffering> ProductOfferings2 { get; set; }
    }
}
