//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class ProductOffering
    {
        public ProductOffering()
        {
            this.PurchaseOrderItems = new HashSet<PurchaseOrderItem>();
            this.SuscriptionItems = new HashSet<SuscriptionItem>();
            this.CreditPacks = new HashSet<CreditPack>();
            this.CreditPackItems = new HashSet<CreditPackItem>();
            this.ProductPackItems = new HashSet<ProductPackItem>();
            this.ProductOfferingPrices = new HashSet<ProductOfferingPrice>();
            this.Products = new HashSet<Product>();
            this.GeoLocationItems = new HashSet<GeoLocationItem>();
            this.Products1 = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public bool Enabled { get; set; }
        public bool OfferedInFrontEnd { get; set; }
        public bool OfferedInBackoffice { get; set; }
        public Nullable<bool> AgencyOfficial { get; set; }
        public Nullable<bool> AgencyMultiBrand { get; set; }
        public int idProduct { get; set; }
        public int idBusinessDomain { get; set; }
        public string UserType { get; set; }
        public Nullable<int> PublishableItemTypeId { get; set; }
    
        public virtual ICollection<PurchaseOrderItem> PurchaseOrderItems { get; set; }
        public virtual ICollection<SuscriptionItem> SuscriptionItems { get; set; }
        public virtual BusinessDomain BusinessDomain { get; set; }
        public virtual ICollection<CreditPack> CreditPacks { get; set; }
        public virtual ICollection<CreditPackItem> CreditPackItems { get; set; }
        public virtual Product Product { get; set; }
        public virtual PublishableItemType PublishableItemType { get; set; }
        public virtual ICollection<ProductPackItem> ProductPackItems { get; set; }
        public virtual ICollection<ProductOfferingPrice> ProductOfferingPrices { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<GeoLocationItem> GeoLocationItems { get; set; }
        public virtual ICollection<Product> Products1 { get; set; }
    }
}
