//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class PublicationSimilarConfigurationOperationType
    {
        public PublicationSimilarConfigurationOperationType()
        {
            this.PublicationSimilarConfigurations = new HashSet<PublicationSimilarConfiguration>();
            this.PublicationSimilarConfigurations1 = new HashSet<PublicationSimilarConfiguration>();
            this.PublicationSimilarConfigurations2 = new HashSet<PublicationSimilarConfiguration>();
            this.PublicationSimilarConfigurations3 = new HashSet<PublicationSimilarConfiguration>();
            this.PublicationSimilarConfigurations4 = new HashSet<PublicationSimilarConfiguration>();
            this.PublicationSimilarConfigurations5 = new HashSet<PublicationSimilarConfiguration>();
        }
    
        public byte P_Id { get; set; }
        public string A_Name { get; set; }
        public string A_MatchKey { get; set; }
    
        public virtual ICollection<PublicationSimilarConfiguration> PublicationSimilarConfigurations { get; set; }
        public virtual ICollection<PublicationSimilarConfiguration> PublicationSimilarConfigurations1 { get; set; }
        public virtual ICollection<PublicationSimilarConfiguration> PublicationSimilarConfigurations2 { get; set; }
        public virtual ICollection<PublicationSimilarConfiguration> PublicationSimilarConfigurations3 { get; set; }
        public virtual ICollection<PublicationSimilarConfiguration> PublicationSimilarConfigurations4 { get; set; }
        public virtual ICollection<PublicationSimilarConfiguration> PublicationSimilarConfigurations5 { get; set; }
    }
}
