//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class PublicationSimilarConfiguration
    {
        public PublicationSimilarConfiguration()
        {
            this.GeoLocationRings = new HashSet<GeoLocationRing>();
            this.GeoLocationRings1 = new HashSet<GeoLocationRing>();
        }
    
        public int P_Id { get; set; }
        public bool A_Enabled { get; set; }
        public Nullable<int> F_Base_PublishableItemType_Id { get; set; }
        public int F_Functionality_Id { get; set; }
        public Nullable<int> F_Filter_PublishableItemType_Id { get; set; }
        public Nullable<int> F_GeoLocationItemType_Id { get; set; }
        public byte F_Brand_OperationType_Id { get; set; }
        public byte F_Model_OperationType_Id { get; set; }
        public byte F_Version_OperationType_Id { get; set; }
        public byte F_Segment_OperationType_Id { get; set; }
        public byte F_Traction_OperationType_Id { get; set; }
        public byte F_SavingPlanType_OperationType_Id { get; set; }
        public Nullable<byte> A_YearLess { get; set; }
        public Nullable<byte> A_YearMore { get; set; }
        public Nullable<short> A_MileageLess { get; set; }
        public Nullable<short> A_MileageMore { get; set; }
        public Nullable<byte> A_PercentagePriceLess { get; set; }
        public Nullable<byte> A_PercentagePriceMore { get; set; }
        public Nullable<byte> A_AmountPriceLess { get; set; }
        public Nullable<byte> A_AmountPriceMore { get; set; }
        public Nullable<int> A_BaseUserTypeId { get; set; }
        public Nullable<int> A_FilterUserTypeId { get; set; }
        public bool A_VerifyCheckContact { get; set; }
        public Nullable<decimal> PurePriceLess { get; set; }
        public Nullable<decimal> PurePriceMore { get; set; }
    
        public virtual GeoLocationItemType GeoLocationItemType { get; set; }
        public virtual PublishableItemType PublishableItemType { get; set; }
        public virtual PublishableItemType PublishableItemType1 { get; set; }
        public virtual PublicationSimilarConfigurationOperationType PublicationSimilarConfigurationOperationType { get; set; }
        public virtual PublicationSimilarConfigurationOperationType PublicationSimilarConfigurationOperationType1 { get; set; }
        public virtual PublicationSimilarConfigurationOperationType PublicationSimilarConfigurationOperationType2 { get; set; }
        public virtual PublicationSimilarConfigurationOperationType PublicationSimilarConfigurationOperationType3 { get; set; }
        public virtual PublicationSimilarConfigurationOperationType PublicationSimilarConfigurationOperationType4 { get; set; }
        public virtual PublicationSimilarConfigurationOperationType PublicationSimilarConfigurationOperationType5 { get; set; }
        public virtual PublicationSimilarConfigurationFunctionality PublicationSimilarConfigurationFunctionality { get; set; }
        public virtual ICollection<GeoLocationRing> GeoLocationRings { get; set; }
        public virtual ICollection<GeoLocationRing> GeoLocationRings1 { get; set; }
    }
}
