//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAutos.Automation.Model.Database
{
    public partial class PublicationExternalAssociation
    {
        public int Id { get; set; }
        public string KeyString { get; set; }
        public int PublicationId { get; set; }
        public int PublicationProviderId { get; set; }
    
        public virtual PublicationProvider PublicationProvider { get; set; }
        public virtual Publication Publication { get; set; }
    }
}
