//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class PublishableItemType
    {
        public PublishableItemType()
        {
            this.Alerts = new HashSet<Alert>();
            this.ContactButtonConfigurations = new HashSet<ContactButtonConfiguration>();
            this.ProductOfferings = new HashSet<ProductOffering>();
            this.PublicationSimilarConfigurations = new HashSet<PublicationSimilarConfiguration>();
            this.PublicationSimilarConfigurations1 = new HashSet<PublicationSimilarConfiguration>();
            this.BusinessDomains = new HashSet<BusinessDomain>();
            this.VehicleBrands = new HashSet<VehicleBrand>();
            this.VehicleModels = new HashSet<VehicleModel>();
            this.VehicleSpecsCategories = new HashSet<VehicleSpecsCategory>();
            this.VehicleVersions = new HashSet<VehicleVersion>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SeoFriendlyName { get; set; }
        public Nullable<int> OrderShow { get; set; }
    
        public virtual ICollection<Alert> Alerts { get; set; }
        public virtual ICollection<ContactButtonConfiguration> ContactButtonConfigurations { get; set; }
        public virtual ICollection<ProductOffering> ProductOfferings { get; set; }
        public virtual ICollection<PublicationSimilarConfiguration> PublicationSimilarConfigurations { get; set; }
        public virtual ICollection<PublicationSimilarConfiguration> PublicationSimilarConfigurations1 { get; set; }
        public virtual ICollection<BusinessDomain> BusinessDomains { get; set; }
        public virtual ICollection<VehicleBrand> VehicleBrands { get; set; }
        public virtual ICollection<VehicleModel> VehicleModels { get; set; }
        public virtual ICollection<VehicleSpecsCategory> VehicleSpecsCategories { get; set; }
        public virtual ICollection<VehicleVersion> VehicleVersions { get; set; }
    }
}
