//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class PublicationVisit
    {
        public int Id { get; set; }
        public Nullable<int> PublicationId { get; set; }
        public Nullable<DateTime> TimeStamp { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Publication Publication { get; set; }
    }
}
