//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class PublishableItemImage
    {
        public int Id { get; set; }
        public int PublishableItemId { get; set; }
        public string FileName { get; set; }
        public short Width { get; set; }
        public short Height { get; set; }
        public Nullable<int> Format { get; set; }
    
        public virtual PublishableItem PublishableItem { get; set; }
    }
}
