//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class PublicationPaper
    {
        public PublicationPaper()
        {
            this.Publications = new HashSet<Publication>();
            this.PublicationPaperDates = new HashSet<PublicationPaperDate>();
        }
    
        public int P_Id { get; set; }
        public string A_Text { get; set; }
        public DateTime A_CreationDate { get; set; }
        public DateTime A_LastModifiedDateText { get; set; }
    
        public virtual ICollection<Publication> Publications { get; set; }
        public virtual ICollection<PublicationPaperDate> PublicationPaperDates { get; set; }
    }
}
