//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class PublicationPaperDateProcess
    {
        public PublicationPaperDateProcess()
        {
            this.PublicationPaperDates = new HashSet<PublicationPaperDate>();
        }
    
        public int P_Id { get; set; }
        public DateTime A_ProcessDate { get; set; }
    
        public virtual ICollection<PublicationPaperDate> PublicationPaperDates { get; set; }
    }
}
