//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class Publication
    {
        public Publication()
        {
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.ListingSponsors = new HashSet<ListingSponsor>();
            this.Conversations = new HashSet<Conversation>();
            this.Clarin365TrackOfTransaction = new HashSet<Clarin365TrackOfTransaction>();
            this.PublicationExternalAssociations = new HashSet<PublicationExternalAssociation>();
            this.PublicationVisits = new HashSet<PublicationVisit>();
            this.Publication1 = new HashSet<Publication>();
            this.Sites = new HashSet<Site>();
        }
    
        public int Id { get; set; }
        public Nullable<DateTime> CreationDate { get; set; }
        public Nullable<DateTime> StartDate { get; set; }
        public Nullable<DateTime> ExpirationDate { get; set; }
        public Nullable<DateTime> EndDate { get; set; }
        public Nullable<int> VisitsCounter { get; set; }
        public Nullable<bool> AutoRePublication { get; set; }
        public int idUser { get; set; }
        public int idPublishableItem { get; set; }
        public Nullable<bool> ActivatedByClienting { get; set; }
        public Nullable<DateTime> LastModificationDate { get; set; }
        public Nullable<bool> ShowInHome { get; set; }
        public Nullable<int> F_PublicationPaper_Id { get; set; }
        public int ShowCountInDetailView { get; set; }
        public Nullable<int> ParentPublicationId { get; set; }
        public int StateId { get; set; }
        public int GeolocationItemId { get; set; }
    
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<ListingSponsor> ListingSponsors { get; set; }
        public virtual ICollection<Conversation> Conversations { get; set; }
        public virtual GeoLocationItem GeoLocationItem { get; set; }
        public virtual ICollection<Clarin365TrackOfTransaction> Clarin365TrackOfTransaction { get; set; }
        public virtual ICollection<PublicationExternalAssociation> PublicationExternalAssociations { get; set; }
        public virtual ICollection<PublicationVisit> PublicationVisits { get; set; }
        public virtual ICollection<Publication> Publication1 { get; set; }
        public virtual Publication Publication2 { get; set; }
        public virtual PublicationPaper PublicationPaper { get; set; }
        public virtual User User { get; set; }
        public virtual PublishableItem PublishableItem { get; set; }
        public virtual ICollection<Site> Sites { get; set; }
    }
}
