//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class PublishableItem
    {
        public PublishableItem()
        {
            this.Publications = new HashSet<Publication>();
            this.PublishableItemImages = new HashSet<PublishableItemImage>();
        }
    
        public int Id { get; set; }
        public Nullable<DateTime> CreationDate { get; set; }
        public Nullable<int> PictureQuantityMax { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> LocalCurrencyPrice { get; set; }
        public Nullable<int> idPriceCurrency { get; set; }
        public Nullable<int> idLocalCurrencyPriceCurrency { get; set; }
        public string SourceName { get; set; }
        public Nullable<bool> CheckPrice { get; set; }
        public string VideoUri { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual ICollection<Publication> Publications { get; set; }
        public virtual ICollection<PublishableItemImage> PublishableItemImages { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
