//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class PurchaseOrderItemDiscount
    {
        public int P_Id { get; set; }
        public Nullable<int> F_PurchaseOrderItem_Id { get; set; }
        public Nullable<int> F_Discount_Id { get; set; }
        public decimal A_PercentajeDiscount { get; set; }
        public decimal A_AmountDiscount { get; set; }
        public DateTime A_CreateDate { get; set; }
    
        public virtual PurchaseOrderItem PurchaseOrderItem { get; set; }
        public virtual Discount Discount { get; set; }
    }
}
