//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class PurchaseOrderItem
    {
        public PurchaseOrderItem()
        {
            this.PurchaseOrderItemDiscounts = new HashSet<PurchaseOrderItemDiscount>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public int idProductPriceCurrency { get; set; }
        public Nullable<int> PurchaseOrder_id { get; set; }
        public Nullable<int> ProductOfferingId { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual ProductOffering ProductOffering { get; set; }
        public virtual ICollection<PurchaseOrderItemDiscount> PurchaseOrderItemDiscounts { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
