//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class RememberDayItem
    {
        public int Id { get; set; }
        public Nullable<int> RememberDayId { get; set; }
        public int GeoStateId { get; set; }
        public int GeoRegionId { get; set; }
        public int GeoCityId { get; set; }
        public int PricingZoneId { get; set; }
        public int ConversationId { get; set; }
    
        public virtual PricingZone PricingZone { get; set; }
        public virtual RememberDay RememberDay { get; set; }
        public virtual Conversation Conversation { get; set; }
        public virtual GeoLocationItem GeoLocationItem { get; set; }
        public virtual GeoLocationItem GeoLocationItem1 { get; set; }
        public virtual GeoLocationItem GeoLocationItem2 { get; set; }
    }
}
