//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAutos.Automation.Model.Database
{
    public partial class Report
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Sp_Name { get; set; }
        public string Category { get; set; }
        public string Sp_Type { get; set; }
    }
}
