//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class SapBillingInfo
    {
        public int ID { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdClienteSap { get; set; }
        public string RazonSocial { get; set; }
        public string Contacto { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string NroFactura { get; set; }
        public Nullable<DateTime> FechaFactura { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> Saldo { get; set; }
    }
}
