//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class SapZone
    {
        public SapZone()
        {
            this.GeoLocationItems = new HashSet<GeoLocationItem>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string SAPZoneCode { get; set; }
        public Nullable<int> PricingZoneId { get; set; }
    
        public virtual PricingZone PricingZone { get; set; }
        public virtual ICollection<GeoLocationItem> GeoLocationItems { get; set; }
    }
}
