//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class SavingPlan
    {
        public int Car_id { get; set; }
        public string A_Financing { get; set; }
        public Nullable<decimal> A_PureFeeValue { get; set; }
        public Nullable<decimal> A_AverageFeeValue { get; set; }
        public Nullable<int> A_NumberOfFees { get; set; }
        public Nullable<int> A_NumberOfAgreedDeliveryFee { get; set; }
        public Nullable<int> F_SavingPlanTransferData_Id { get; set; }
        public int F_SavingPlanType_Id { get; set; }
    
        public virtual SavingPlanType SavingPlanType { get; set; }
        public virtual Car Car { get; set; }
        public virtual SavingPlanTransferData SavingPlanTransferData { get; set; }
    }
}
