//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class SavingPlanTransferData
    {
        public SavingPlanTransferData()
        {
            this.SavingPlans = new HashSet<SavingPlan>();
        }
    
        public int P_Id { get; set; }
        public Nullable<int> A_NumberOfPaidFees { get; set; }
        public Nullable<decimal> A_TransferAmmount { get; set; }
    
        public virtual ICollection<SavingPlan> SavingPlans { get; set; }
    }
}
