//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class SecurityRole
    {
        public SecurityRole()
        {
            this.SecurityUsers = new HashSet<SecurityUser>();
        }
    
        public long id { get; set; }
        public long version { get; set; }
        public string authority { get; set; }
    
        public virtual ICollection<SecurityUser> SecurityUsers { get; set; }
    }
}
