//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class SecurityUser
    {
        public SecurityUser()
        {
            this.AuditCatalogs = new HashSet<AuditCatalog>();
            this.SecurityRoles = new HashSet<SecurityRole>();
        }
    
        public long id { get; set; }
        public long version { get; set; }
        public bool account_expired { get; set; }
        public bool account_locked { get; set; }
        public bool enabled { get; set; }
        public string password { get; set; }
        public string applicationToken { get; set; }
        public bool password_expired { get; set; }
        public string username { get; set; }
    
        public virtual ICollection<AuditCatalog> AuditCatalogs { get; set; }
        public virtual ICollection<SecurityRole> SecurityRoles { get; set; }
    }
}
