//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class Site
    {
        public Site()
        {
            this.ClientUsers = new HashSet<ClientUser>();
            this.Conversations = new HashSet<Conversation>();
            this.Publications = new HashSet<Publication>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Client { get; set; }
        public string SapAdvertiserCode { get; set; }
        public string Street { get; set; }
        public string StreetNumber { get; set; }
        public string Floor { get; set; }
        public string Department { get; set; }
        public string ZipCode { get; set; }
        public int GeoLocationItem { get; set; }
        public bool Headquarter { get; set; }
        public bool HasStore { get; set; }
        public bool HasLogo { get; set; }
        public string StoreUrl { get; set; }
        public string AboutTheAgency { get; set; }
        public string LocationCoordinates { get; set; }
        public Nullable<int> LogoId { get; set; }
        public int Type { get; set; }
    
        public virtual Client Client1 { get; set; }
        public virtual ICollection<ClientUser> ClientUsers { get; set; }
        public virtual ICollection<Conversation> Conversations { get; set; }
        public virtual GeoLocationItem GeoLocationItem1 { get; set; }
        public virtual SiteType SiteType { get; set; }
        public virtual ICollection<Publication> Publications { get; set; }
    }
}
