//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class SourceSection
    {
        public SourceSection()
        {
            this.PhoneContacts = new HashSet<PhoneContact>();
            this.Messages = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PhoneContact> PhoneContacts { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
