//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class Suscription
    {
        public Suscription()
        {
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
        }
    
        public int Id { get; set; }
        public string State { get; set; }
        public string Name { get; set; }
        public Nullable<DateTime> CreationDate { get; set; }
        public Nullable<DateTime> ActivationDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> BilledPeriodsCounter { get; set; }
        public Nullable<DateTime> LastBilling { get; set; }
        public int idAgencyUser { get; set; }
        public Nullable<DateTime> ExpirationDate { get; set; }
    
        public virtual ClientUser ClientUser { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
    }
}
