//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class Tag
    {
        public int id { get; set; }
        public string KeyString { get; set; }
        public string Content { get; set; }
        public Nullable<int> idBusinessDomain { get; set; }
    
        public virtual BusinessDomain BusinessDomain { get; set; }
        public virtual BusinessDomain BusinessDomain1 { get; set; }
    }
}
