//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAutos.Automation.Model.Database
{
    public partial class UsedCar
    {
        public int Car_id { get; set; }
        public int Mileage { get; set; }
        public string Plate { get; set; }
        public int idColour { get; set; }
    
        public virtual Colour Colour { get; set; }
        public virtual Car Car { get; set; }
    }
}
