//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DeAutos.Automation.Model.Database
{
    public partial class UserCustomerGroup
    {
        public long P_Id { get; set; }
        public Nullable<int> F_Customer_Id { get; set; }
        public Nullable<int> F_CustomerGroup_Id { get; set; }
    
        public virtual CustomerGroup CustomerGroup { get; set; }
        public virtual User User { get; set; }
    }
}
