//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class VehicleVersion
    {
        public VehicleVersion()
        {
            this.CatalogSponsors = new HashSet<CatalogSponsor>();
            this.ListedVehicles = new HashSet<ListedVehicle>();
            this.Cars = new HashSet<Car>();
            this.PublishableItemTypes = new HashSet<PublishableItemType>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SeoFriendlyName { get; set; }
        public int idVehicleModel { get; set; }
        public int idVehicleSegment { get; set; }
        public Nullable<DateTime> LastChangeDate { get; set; }
        public Nullable<DateTime> CreationDate { get; set; }
    
        public virtual ICollection<CatalogSponsor> CatalogSponsors { get; set; }
        public virtual ICollection<ListedVehicle> ListedVehicles { get; set; }
        public virtual VehicleModel VehicleModel { get; set; }
        public virtual VehicleSegment VehicleSegment { get; set; }
        public virtual ICollection<Car> Cars { get; set; }
        public virtual ICollection<PublishableItemType> PublishableItemTypes { get; set; }
    }
}
