//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class Vehicle
    {
        public Vehicle()
        {
            this.AttributeDefinitions = new HashSet<AttributeDefinition>();
            this.SpecialAttributeDefinitions = new HashSet<SpecialAttributeDefinition>();
            this.PublishableItemPaymentMethods = new HashSet<PublishableItemPaymentMethod>();
        }
    
        public int PublishableItem_id { get; set; }
        public string SellerComments { get; set; }
        public Nullable<short> UploadedPhotosQuantity { get; set; }
        public int idFuel { get; set; }
        public Nullable<short> Year { get; set; }
    
        public virtual Fuel Fuel { get; set; }
        public virtual Car Car { get; set; }
        public virtual PublishableItem PublishableItem { get; set; }
        public virtual ICollection<AttributeDefinition> AttributeDefinitions { get; set; }
        public virtual ICollection<SpecialAttributeDefinition> SpecialAttributeDefinitions { get; set; }
        public virtual ICollection<PublishableItemPaymentMethod> PublishableItemPaymentMethods { get; set; }
    }
}
