//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class VehicleModel
    {
        public VehicleModel()
        {
            this.BannerCampaigns = new HashSet<BannerCampaign>();
            this.PrelistingToVehicleModels = new HashSet<PrelistingToVehicleModel>();
            this.AutoPublicationVehicleModelYears = new HashSet<AutoPublicationVehicleModelYear>();
            this.CatalogSponsors = new HashSet<CatalogSponsor>();
            this.CatalogSponsorCompares = new HashSet<CatalogSponsorCompare>();
            this.ListingSponsorVehicleModelYears = new HashSet<ListingSponsorVehicleModelYear>();
            this.PeopleToBeContacteds = new HashSet<PeopleToBeContacted>();
            this.VehicleModelSellerClients = new HashSet<VehicleModelSellerClient>();
            this.AuditCatalogs = new HashSet<AuditCatalog>();
            this.VehicleVersions = new HashSet<VehicleVersion>();
            this.PublishableItemTypes = new HashSet<PublishableItemType>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SeoFriendlyName { get; set; }
        public int idVehicleBrand { get; set; }
        public Nullable<DateTime> LastChangeDate { get; set; }
        public Nullable<DateTime> CreationDate { get; set; }
        public Nullable<bool> isPublishableInLanding { get; set; }
    
        public virtual ICollection<BannerCampaign> BannerCampaigns { get; set; }
        public virtual ICollection<PrelistingToVehicleModel> PrelistingToVehicleModels { get; set; }
        public virtual ICollection<AutoPublicationVehicleModelYear> AutoPublicationVehicleModelYears { get; set; }
        public virtual ICollection<CatalogSponsor> CatalogSponsors { get; set; }
        public virtual ICollection<CatalogSponsorCompare> CatalogSponsorCompares { get; set; }
        public virtual ICollection<ListingSponsorVehicleModelYear> ListingSponsorVehicleModelYears { get; set; }
        public virtual ICollection<PeopleToBeContacted> PeopleToBeContacteds { get; set; }
        public virtual ICollection<VehicleModelSellerClient> VehicleModelSellerClients { get; set; }
        public virtual VehicleBrand VehicleBrand { get; set; }
        public virtual ICollection<AuditCatalog> AuditCatalogs { get; set; }
        public virtual ICollection<VehicleVersion> VehicleVersions { get; set; }
        public virtual ICollection<PublishableItemType> PublishableItemTypes { get; set; }
    }
}
