//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class VehicleSpecsCategory
    {
        public VehicleSpecsCategory()
        {
            this.AttributeDefinitions = new HashSet<AttributeDefinition>();
            this.VehicleSpecsCategory1 = new HashSet<VehicleSpecsCategory>();
            this.PublishableItemTypes = new HashSet<PublishableItemType>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> idVehicleSpecsCategoryParent { get; set; }
    
        public virtual ICollection<AttributeDefinition> AttributeDefinitions { get; set; }
        public virtual ICollection<VehicleSpecsCategory> VehicleSpecsCategory1 { get; set; }
        public virtual VehicleSpecsCategory VehicleSpecsCategory2 { get; set; }
        public virtual ICollection<PublishableItemType> PublishableItemTypes { get; set; }
    }
}
