//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class VehicleBrand
    {
        public VehicleBrand()
        {
            this.PrelistingToVehicleBrands = new HashSet<PrelistingToVehicleBrand>();
            this.ListingSponsorVehicleBrands = new HashSet<ListingSponsorVehicleBrand>();
            this.VehicleBrandAutoPublications = new HashSet<VehicleBrandAutoPublication>();
            this.BrandSavingPlans = new HashSet<BrandSavingPlan>();
            this.VehicleBrandSellerClients = new HashSet<VehicleBrandSellerClient>();
            this.VehicleModels = new HashSet<VehicleModel>();
            this.ClientUsers = new HashSet<ClientUser>();
            this.PublishableItemTypes = new HashSet<PublishableItemType>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SeoFriendlyName { get; set; }
        public Nullable<DateTime> LastChangeDate { get; set; }
        public Nullable<DateTime> CreationDate { get; set; }
    
        public virtual ICollection<PrelistingToVehicleBrand> PrelistingToVehicleBrands { get; set; }
        public virtual ICollection<ListingSponsorVehicleBrand> ListingSponsorVehicleBrands { get; set; }
        public virtual ICollection<VehicleBrandAutoPublication> VehicleBrandAutoPublications { get; set; }
        public virtual ICollection<BrandSavingPlan> BrandSavingPlans { get; set; }
        public virtual ICollection<VehicleBrandSellerClient> VehicleBrandSellerClients { get; set; }
        public virtual ICollection<VehicleModel> VehicleModels { get; set; }
        public virtual ICollection<ClientUser> ClientUsers { get; set; }
        public virtual ICollection<PublishableItemType> PublishableItemTypes { get; set; }
    }
}
