//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class VehicleSegment
    {
        public VehicleSegment()
        {
            this.VehicleVersions = new HashSet<VehicleVersion>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SeoFriendlyName { get; set; }
        public Nullable<int> OrderHomeSearch { get; set; }
        public int F_Hub_Rubro_Id { get; set; }
    
        public virtual HubRubro HubRubro { get; set; }
        public virtual ICollection<VehicleVersion> VehicleVersions { get; set; }
    }
}
