//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace DeAutos.Automation.Model.Database
{
    public partial class ZonalSupplementArea
    {
        public ZonalSupplementArea()
        {
            this.GeoLocationItems = new HashSet<GeoLocationItem>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public bool Enabled { get; set; }
    
        public virtual ICollection<GeoLocationItem> GeoLocationItems { get; set; }
    }
}
